phraseDict = {
    'positivity' : [
        ["I\'m on that positivity flow, I\'ll blind the darkness with my glow, we out here letting everyone know, it\'s going down SO LETS GO!!!!"],
        ["The most important thing you will ever wear is your attitude."],
        ["Dr. Barbara Fredrickson (a medical researcher) discovered that experiencing positive emotions broadens people\'s minds and builds their resourcefulness in ways that help them become more resilient to adversity."],
        ["Once you replace your negative thoughts with positive ones, you\'ll start having positive results. -- Willie Nelson"],
        ["I always try to look on the optimistic side, but I am realistic enough to know that life is a complex matter. -- Walt Disney"],
        ["You can\'t make positive choices for the rest of your life without an environtment that makes those choices easy, natural, and enjoyable. -- Deepak Chopra"],
        ["Perpetual optimism is a force multiplier. -- Colin Powell"],
        ["Failures are simply steps you must climb to reach to the door of success. -- Xinthral"],
        ["Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you. -- Marry Lou Retton"],
        ["If you are going to dwell on life, then dwell on the beauty of life; watch the stars and see yourself running through them. -- Marcus Aurelius (paraphased)"],
        ["When things go wrong, don't go with them. -- Elvis Presley"],
        ["If you think the world has you cornered, the reality is that just makes the path forward that much clearer -- Inspired by Stephen Richards"],
        ["An arrow can only be shot by pulling it backwards, so remember that when you feel like life is pulling you down. Life is preparing to launch you to the target, so stay focused and keep aiming at where you want to be. -- Xinthral (adapted)"],
        ["Each great day starts with a great attitude, each great week starts with a great day, each great month starts with a great week, and each great year starts with a great month.  If you want to start living a great life, then start with your attitude. Power through positivity is a lifestyle. -- Xinthral (adapted)"],
        ["I am in charge of how I feel, and today I am choosing happiness."],
        ["Learn from yesterday, live for today, hope for tomorrow. -- Albert Einstein"],
        ["The sun is a daily reminder that when we survive the darkness, there is light on the other side. -- Xinthral (adapted) from S. Ajna"],
        ["If you want the cooperation of humans around you, you must make them feel important; and you do that by being genuine and humble. -- Nelson Mandela"],
        ["One day, in retrospect, the years of struggle will strike you as the most beautiful (years of your life). -- Sigmund Freud"],
        ["The future belongs to those who believe in the beauty of their dreams. -- Eleanor Roosevelt"],
        ["The greatness of a man is not how much wealth he acquires, but in his integrity and ability to affect those around him positively. -- Bob Marley"],
        ["History has shown us that courage can be contagious and hope can take on a life of it\'s own. -- Michelle Obama"],
        ["Positivity can turn the impossible in the possible. I realize that \'Im\' the only difference between possible and Impossible. -- Xinthral"],
        ["The most common way people give up their power is by thinking they don\'t have any. Go forth and be powerful. -- Alice Walker (appended)"],
        ["Everyone has a history, it is up to you to decide what to do with it.  Some repeat it, some learn from it; but the really special ones use it to help others. -- John Mark Green"],
        ["People will forget the awkward things you said, and the embarrising things you did, but people never forget the way you made them feel. -- Maya Angelou (adapted)"],
        ["Optimist are usually wrong about how the world works, but all the positive changes our world has seen, was done by an optimist who refused to accept the world as it is. -- Thomas Friedman (adapted)"],
        ["Keep looking up...that\'s the secret to life. -- Charlie Brown"],
        ["\'Gotta have a little sadness once in a while so you know when the good times come. I\'m wiaiting on the good tiems now.\' -- Bob Ross said this while painting just after his wife passed. This is strength."],
        ["The first thought that goes through your head is what you have been conditioned to think, however the next is what defines you so make sure you think it through. -- Mom"]
    ],
    'inspirational' : [
        ["You can choose to love, or you can choose to hate. But you only have enough energy for one, so choose wisely. -- Dad"],
        ["You can, you should, and if you\'re brave enough, you will. -- Stephen King"],
        ["Happiness is a (measurement of the) quality of the soul, not a function of one\'s material circumstances. -- Aristotle"],
        ["A powerful attitude awakens inner strength, energy, motivation, and initiative. -- Remez Sasson"],
        ["Yesterday is not ours to recover, but tomorrow is ours to win or lose. -- Lyndon B. Johnson"],
        ["I\'d rather die exhausted, than to live with regrets. -- T3chnopanda"],
        ["You\'re off to great places, today is your day. Your mountain is waiting, so get on your way. -- Dr. Seuss"],
        ["No one is perfect, that\'s why pencils have erasers. -- Wolfgang Riebe"],
        ["It always seems impossible until it is done. -- Nelson Mandela"],
        ["The sun (himself) is weak when he first rises, and gathers strength and corage as the day gets on. -- Charles Dickens"],
        ["Sucess is not a result of winning or losing, it's a measurement of your ability to keep making progress; regardless -- T3chnopanda"],
        ["Positivity is contagious, Inspiration is infectious, and compassion is priceless. -- Xinthral"],
        ["Balance in life isn\'t an equation, it\'s a perception. If you want to find balance in life, start by balancing your perspective. -- Xinthral"],
        ["When you feel the weight of the world barring down on you and you don't know if you can take it, just remember that time and pressure are the required elements to make diamonds."],
        ["If you want people to build a boat, don\'t tell them what to do; teach them to long for the endless immensity of the sea, and then they will want to build a boat. -- Antoine de Saint Expery (adapted)"],
        ["The true measure of success is how many times you can bounce back from failure. -- Stephen Richards"],
        ["You could be labeled freak, or you could be labeled unique; the determining factor is your perspective, be mindful of where it\'s at. -- Inspired by a quote from Christian Baloga"],
        ["Learn from yesterday, live for today, hope for tomorrow. -- Albert Einstein"],
        ["Our greatest glory is not never falling, but in the rising everytime we fall. -- Confucious (translated)"],
        ["Success is not final, failure is not fatal: it is the courage to continue that counts. -- Winston S. Churchill"],
        ["We can complain because rose bushes have thorns, or we can rejoice because thorn bushes have roses. -- Abraham Lincoln"],
        ["Efforts and courage are not enough without purpose and direction -- JFK"],
        ["You must never be fearful about what you are doing when it is right. -- Rosa Parks"],
        ["A small body of determined spirits fired by an unquenchable faith in their mission can alter the course of history. -- Mahatma Gandhi"],
        ["Unable are the loved to die, for love is immortal. -- Emily Dickinson"],
        ["People seldom see the halting and painful steps by which the most success is achieved. -- Anne Sullivan (adapted)"],
        ["The quality, not the longevity of ones life is what is important. -- MLK Jr."],
        ["I have learned that success is to be measured, not so much by the position that one has reached in life, but by the obstacles which one had to overcome while trying to succeed. -- Booker T. Washington (adapted)"],
        ["The best way to predict the future, is to create it. -- Abraham Lincoln"],
        ["Just remember, up until this point you\'ve survived the worst things the world could throw at you. You\'re strong than you realize. -- Xinthral"],
        ["A man named Dashrath Manjhi spent 22 years cutting down a mountain to reduce the distance from his village to the hospital (70km down to 1km) so no one else would die from lack of medical care like his wife."],
        ["When you fail to prepare, you are preparing to fail. -- Benjamin Franklin"]
    ],
    'stream': [
        ["Who\'s that cummin up in here with the BDE!?!? -- T3chnopanda"],
        ["Rando: I waited 18 minutes for this to end so quickly? T3chnopanda: I waited my whole life to have sex and it only took 30 seconds."],
        ["You done fk\'d up A-A-ron!"],
        ["Turn her over and then BAM, up the butt. -- Gordon Ramsey"],
        ["Every hole is a goal. -- T3chnopanda"],
        ["I can literally beat my meat, and not have to take it out to dinner. -- T3chnopanda"],
        ["The truth, will out. -- The_Skeletor_"],
    ],
    'funny': [
        ["You can\'t make something idiot-proof cause God designs the idiots, and he\'s a better bot designer than you. -- Xinthral"],
        ["Strong people don\'t put people down, they lift people up. -- Darth Vader"],
        ["You matter....Unless you multiply yourself by the speed of light. Then you energy -- Reddit"],
        ["In May 2019, it was reported that students had invented a bacteria that can eat plastic from the oceans and turn it into water. The future is waiting, will you go after it or let it pass you by?"],
        ["Arms on your chairs are just chairs for your arms."],
        ["I heard a trick on how to turn $40 into $400, want to know the secret?", "Put $40 worth of gas in your vehicle and drive your stupid ass to work. -- Chief Chuck"],
    ],
    'shower': [
        ["Men probably bond so well with dogs because our society shows less compassion to males and dogs help suppliment that basic human need."],
        ["In 2014, Mathematicians solved the problem of superpermutations. In 2019, it was discovered that a random 4-chan user had solved it and posted their results in 2011"],
        ["The ability to forget is my superpower, less we'd be forced to carry the full weight of our history. -- xinthral"],
        ["By learning to be okay with being alone, you allow yourself to be more choosy with whom you invite into your space. -- Mandy Hale (adapted)"],
        ["I walk slowly, but I never walk backwards. -- Abraham Lincoln"],
        ["Death is nature's way of saying, \'Your table is ready.\' -- Robin Williams"],
        ["The bitterest tears shed over graves are for words left unsaid and deeds left undone. -- Harriet Beacher-Stower"],
        ["Music is the shorthand for emotion. -- Leo Tolstoy"],
        ["They said that Rosa Parks sat down in the front because she was too tired to reach the back, her response was \'The only tired I was, was tired of giving in.\'"],
        ["Every day I wake I play God, for I have the power to change the world!. -- Xinthral"],
        ["Tradition is just peer pressure from dead people. -- Reddit"],
    ],
    'nerd': [
        ["Through entropy, you will be immortalized forever as it cannot be undone. -- Xinthral"],

    ]
}
